### ISSUE TITLE
CTRL-I working only in tmux session

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#5]
If you try to use it without being in a session it reload the same screen you are already in, but does not create/launch any new session in TERMINAL.

**Comment by SleepyBag** [comment]
I personally use konsole and didn't test for other terminals. Which terminal emulator do you use? I'll look into it.
If you are interested in, you could also look into `function/_fuzzy-fs-open-shell`, which is straightforward, and make a PR.

**Comment by ddnexus** [comment]
I tried in `gnome-terminal` and in `tilix` and both work only when you are already in a tmux session.

I tried to check the function that you are pointing out, and while I was doing that, I discovered a weird thing: if you enter in `~/.zplug`, fuzzy-fs is not able to enter in any child dir there.

**Comment by SleepyBag** [comment]
That's weird. How do your `~/.zplug` looks like? And did you update after the last commit?

**Comment by SleepyBag** [comment]
Maybe you could paste the output of `exa -l --git` in your `~/.zplug`. That may be helpful.

**Comment by ddnexus** [comment]
It was already updated of course.
```
exa -la --git
drwxr-xr-x    - dd 27 Oct 16:44 .git
drwxr-xr-x    - dd 12 Apr  2017 .github
.rw-r--r--  236 dd 28 Sep 13:16 .gitignore
.rw-r--r--  891 dd 28 Sep 13:19 .travis.yml
drwxr-xr-x    - dd 12 Apr  2017 autoload
drwxr-xr-x    - dd 12 Apr  2017 base
drwxr-xr-x    - dd 26 Oct 17:35 bin
drwxrwxr-x    - dd 27 Oct 16:29 cache
drwxr-xr-x    - dd 12 Apr  2017 doc
lrwxrwxrwx   42 dd 28 Sep 13:19 init.zsh -> /home/dd/.zplug/repos/zplug/zplug/init.zsh
drwxr-xr-x    - dd 27 Oct 16:51 log
.rw-r--r-- 1.3k dd 28 Sep 13:19 Makefile
drwxr-xr-x    - dd 12 Apr  2017 misc
.rw-rw-r--  590 dd 26 Oct 20:47 packages.zsh
.rw-r--r--  15k dd 28 Sep 13:16 README.md
drwxr-xr-x    - dd 27 Oct  5:52 repos
drwxr-xr-x    - dd 12 Apr  2017 test
.rw-rw-r--  54k dd 27 Oct 16:29 zcompdump
```

**Comment by SleepyBag** [comment]
Is your ~/.zplug a git repo? `ffs` determines whether it is in a git repo by `git status`. If it is, `ffs` take the 8th column from the output of exa. Otherwise it takes the 7th. Maybe this is not how `exa` work? If `git status` returns 0 in `.zplug`, but `exa` doesn't print the git line (as is shown in your paste), `ffs` will take the wrong column.

**Comment by ddnexus** [comment]
ideed it does not work on any git repo! 

> ffs determines whether it is in a git repo by git status

so what if there is no git installed? Not sure that running a command is a good idea. And why a git repo would be any different from a regular dir? I don't see any difference between a git repo and a regular dir here.

**Comment by SleepyBag** [comment]
It's not about git itself, but about `exa`.
`exa` print the result in the following format:

```
.rw-rw-r--  590 dd 26 Oct 20:47 packages.zsh
```

and I take the 7th column as the result file name. However, when there is `--git` parameter and `exa` is run in a git repo. The output should be as

```
.rw-rw-r--  590 dd 26 Oct 20:47 --- packages.zsh
```

where the new column of dashes is the git status of this file. And then I have to take the 8th column.

So why doesn't your `exa -l --git` print git status in a git repo? This is the problem.

If you'd like to know why don't I just take the last column, it's because there's links like

```
lrwxrwxrwx   42 dd 28 Sep 13:19 init.zsh -> /home/dd/.zplug/repos/zplug/zplug/init.zsh
```

**Comment by ddnexus** [comment]
I see. 
It's probably a difference in the version: 
```
exa --version
exa v0.9.0
```
The weird thing with my version is that it accepts the `--git` param, but it's nowhere to be found in the `man exa` aznd it looks like it doesn't do anything.

Maybe you can check the version and react in a different way.

**Comment by ddnexus** [comment]
I see that the version is the last one :/

**Comment by SleepyBag** [comment]
Yeah that's quite strange. I'm using version `v0.9.0`, too.

**Comment by ddnexus** [comment]
```
git --version   
git version 2.27.0
```

**Comment by ddnexus** [comment]
git has nothing to do. There is [some interesting info](https://the.exa.website/features/git) at the end of the page.

**Comment by ddnexus** [comment]
For some reason my version is not supporting git... but you could probably know that by checking the version. It should contain `+git` as it says in that page.

**Comment by ddnexus** [comment]
libgit2. What version do you have? mine is just 0.28.5+dfsg.1, while the [last version](https://github.com/libgit2/libgit2/releases) is a lot higher

**Comment by SleepyBag** [comment]
This is quite helpful. But however... There isn't any other information in my `exa --version`. The result is

```
exa v0.9.0
```

I'll look into this later. 

BTW, I pushed a new version and now you can use `ls` instead of `exa` temporarily by adding the following line in your .zshrc:

```
export FUZZY_FS_LS_COMMAND=ls
```

**Comment by ddnexus** [comment]
Thank you! I really like `exa` now, so I will not go back to ls :smile: . I will live with the bug in the git dirs for now.

Working around it should not be difficult... maybe just counting the columns in the `--header`.

**Comment by SleepyBag** [comment]
Yes you're right. I didn't know such an option of `exa`. Fixed it now (though it wasn't that easy).

**Comment by ddnexus** [comment]
Thank you. The git problem is fixed now,.

I am wondering whether a simple variable would be better to enable/disable the behavior by the user himself.

A possible good strategy would be having a ffs-exa-git variable false by default. If the user knows his OS supports it AND he is interested in having it THEN he can enable it.

That should simplify the code, plus, it will allow the user to opt-in the git stuff willingly and if needed. Indeed it is quite expensive and if you are using a different tool to manage your git repos, it might be pointless and just eat up resources.

**Comment by ddnexus** [comment]
BTW, the `CTRL-I` command is quite broken now.

Here is what I get after CTRL-I a couple of times and then CTRL-Q
```
fs
[5] 1862166
[5]  + exit 1     $TERMINAL --workdir $pwd &> /dev/null
                                                       [5] 1863158
[5]  + exit 1     $TERMINAL --workdir $pwd &> /dev/null
                                                       %                                                                                             
```
sometimes it prints the command it in the filter itself and the text on the terminal gets messed up.

**Comment by ddnexus** [comment]
I think the problem is the `--workdir` param for gnome-terminal.

```
$ gnome-terminal --workdir $pwd
# Failed to parse arguments: Unknown option --workdir

$ gnome-terminal $pwd # => works
$ gnome-terminal      # => works as well and cd into the $pwd automatically
```

**Comment by ddnexus** [comment]
Tried to modify the function removing the extra `--workdir`. It opens a new terminal window as expected, but here is what happens:

```
/etc/zsh/zshrc:111: compinit: function definition file not found
/home/dd/.zshrc:100: promptinit: function definition file not found
/home/dd/.zshrc:101: compinit: function definition file not found
/home/dd/.zplug/repos/zplug/zplug/autoload/init.zsh:16: colors: function definition file not found
polling.zsh:17: add-zsh-hook: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::get_interfaces:49: regexp-replace: function definition file not found
__zplug::core::core::prepare:67: compinit: function definition file not found
[zplug] ERROR: The loading of zplug was discontinued.
__zplug::core::load::from_cache:24: compinit: function definition file not found
(anon):8: is-at-least: function definition file not found
x2% 
```

**Comment by ddnexus** [comment]
BTW, the param for gnome-terminal would be `--working-directory`. I am wondering if we need a template variable in order to compose different commands for different terminal apps.

**Comment by SleepyBag** [comment]
> I am wondering whether a simple variable would be better to enable/disable the behavior by the user himself.

It's done now. The git feature is disabled by default. You can toggle it by `--git` parameter.

**Comment by SleepyBag** [comment]
We have talked too much in this issue. If you have any further question, let's open another.

**Comment by ddnexus** [comment]
> We have talked too much in this issue. If you have any further question, let's open another.

Yes, you are right :).

**Comment by SleepyBag** [comment]
> Tried to modify the function removing the extra --workdir. It opens a new terminal window as expected, but here is what happens:

This should be fixed now. I made some variables like `SHELL` local in the main function so they weren't passed to the subprocess. I changed this behavior in the lastest commit.

**Comment by ddnexus** [comment]
Indeed it works if I override the function removing `--workdir`. Thank you.
If there is no way to set it in a variable, then I guess I will have to find a way to override it so it will survive an update.

**Comment by SleepyBag** [comment]
I'm working on it. Will be released soon.

**Comment by ddnexus** [comment]
I talked too soon: it does open the new terminal window, but it messed up the ffs panel with the command (written in the filter field):
```
[6]   + done        $ffs_terminal &> /dev/null
```
adding a new line to the filter line that messes up the rest of the panel

**Comment by SleepyBag** [comment]
Do me a favor:
What terminal emulators are you using and how do they specify working directory?

I need to define a list to support some normal emulators.

Of course I will provide a variable to customize, too.

**Comment by SleepyBag** [comment]
Fixed.

> I talked too soon: it does open the new terminal window, but it messed up the ffs panel with the command (written in the filter field):
> [6]   + done        $ffs_terminal &> /dev/null

It's solved, too.

**Comment by ddnexus** [comment]
`gnome-terminal` is the official ubuntu terminal. Here is how you can use it:

```
$ gnome-terminal --working-directory $pwd  # explicit
$ gnome-terminal $pwd # => works
$ gnome-terminal      # => works as well and cd into the $pwd automatically
```
However there are also other params that could be added... for example `--tab`. If you add it it will open the new session as a tab in the same window. Again, no need to add any argument. In the spirit of the `tmux` command a tab would be my preferred way to open a new shell session.

I was thinking to use a variable that the user can set as a format string, so it could be interpolated with the variables in the function by using printf and executed. That way everybody can customize it for its own terminal and you will not have to know every possible string for every possible terminal.

**Comment by ddnexus** [comment]
just saw your commit: it's even simpler than what I was suggesting! :+1:

**Comment by ddnexus** [comment]
Still does not work :/
The problem is that it just closes the ffs panel, but does not open the shell instance. No more command messing up, but still no new shell.

**Comment by SleepyBag** [comment]
Sorry for that. Just added a new commit. It should work now.

**Comment by ddnexus** [comment]
Bingo! Now it works, also in a new tab! Thank you!

ffs is starting to be great!!!
